org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8
mod_id=insulin
mod_name=Insulin
mod_group_id=net.fly.insulin
mod_version=0.1.0
mod_authors=Fly
mod_license=GPL-3.0-only
mod_description=Son, are you meshing your chunks again?
selected_loaders=fabric,forge
selected_versions=[1.20, 1.21)
selected_java_versions=[1.20, 1.21)=17/21
use_mixins=true
publish_modrinth=false
publish_curseforge=false
publish_changelog=No changelog provided.
symbol_preset=flysstyle
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=/nix/store/ld0alp2hg69xy9n80cnm647d0xmkqrsi-openjdk-8u502-b01/lib/openjdk,/nix/store/04cqkgis3i4b0fm42h5s77i96dp9gmyg-openjdk-17.0.20+2/lib/openjdk,/nix/store/04cqkgis3i4b0fm42h5s77i96dp9gmyg-openjdk-17.0.20+2/lib/openjdk,/nix/store/102gxd1lf8cniz9zzsxn7mdmnar8w0jz-openjdk-21.0.12+2/lib/openjdk
java_8_home=/nix/store/ld0alp2hg69xy9n80cnm647d0xmkqrsi-openjdk-8u502-b01/lib/openjdk
java_16_home=/nix/store/04cqkgis3i4b0fm42h5s77i96dp9gmyg-openjdk-17.0.20+2/lib/openjdk
java_17_home=/nix/store/04cqkgis3i4b0fm42h5s77i96dp9gmyg-openjdk-17.0.20+2/lib/openjdk
java_21_home=/nix/store/102gxd1lf8cniz9zzsxn7mdmnar8w0jz-openjdk-21.0.12+2/lib/openjdk
